name: tokenized-strategy-ape-mix

plugins:
  - name: solidity
  - name: etherscan
  - name: hardhat
  - name: infura

default_ecosystem: ethereum
dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.8.2
  - name: BaseStrategy
    github: yearn/tokenized-strategy
    branch: master
    contracts_folder: src
    exclude:
      - test/**/*

solidity:
  import_remapping:
    - "@openzeppelin/contracts=openzeppelin/v4.8.3"
    - "@BaseStrategy=Basestrategy"

ethereum:
  default_network: mainnet-fork
  mainnet_fork:
    default_provider: hardhat

hardhat:
  fork:
    ethereum:
      mainnet:
        upstream_provider: infura