name: lender-borrower-bot

plugins:
  - name: solidity
  - name: infura
  - name: polygon
  - name: alchemy

default_ecosystem: ethereum

ethereum:
  default_network: mainnet
  mainnet:
    default_provider: infura

polygon:
  default_network: mainnet
  mainnet:
    default_provider: alchemy
